name: Deploy GH-Pages

on:
  push:
    branches: [ main, master ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      REDIRECT_URL: https://wmc-ahif-2021.github.io/VisualNovel/
      UPDATE_SCRIPT: https://gist.githubusercontent.com/Luna-Klatzer/a6f57a7ad7d79dc0a90115846cc98945/raw/756317baa73c904e3c2afef8cd10f3509dfc8dea/insert-html-banner.py
      SCRIPT_FILE_NAME: insert-html-banner.py
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Installs dependencies
        run: |
          npm install
      - name: Download Update Script
        run: curl ${{ env.UPDATE_SCRIPT }} > ${{ env.SCRIPT_FILE_NAME }}
      - name: Insert Disclaimer Header
        run: python insert-html-banner.py
      - name: Build Files using Parcel
        run: parcel build src/index.html --public-url ${{ env.REDIRECT_URL }} --dist-dir .
      - name: Add Local Identification Config
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name  "github-actions"
      - name: Commit changes to main
        run: |
          git add .
          git commit -m "Updated parcel build"
          git push origin +main:gh-pages --force
